import { ResumeData } from '../types/resume';

export const createEmptyResume = (title = 'Untitled Resume', targetRole = 'Software Engineer'): ResumeData => ({
  id: `resume-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  title,
  targetRole,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  personalInfo: {
    fullName: 'Alex Morgan',
    jobTitle: targetRole || 'Senior Software Engineer',
    email: 'alex.morgan@example.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    website: 'https://alexmorgan.dev',
    linkedin: 'linkedin.com/in/alexmorgan',
    github: 'github.com/alexmorgan',
  },
  summary:
    'Results-driven Senior Software Engineer with over 6 years of experience building high-scale web applications, microservices, and distributed cloud architectures. Proven track record of improving system performance by 40% and leading cross-functional teams to ship products used by millions.',
  experience: [
    {
      id: 'exp-1',
      company: 'TechCorp Solutions',
      position: 'Senior Frontend Engineer',
      location: 'San Francisco, CA',
      startDate: '2022-01',
      endDate: '',
      current: true,
      description: 'Lead frontend architect for core SaaS analytics platform.',
      highlights: [
        'Architected React + TypeScript micro-frontend application serving over 500k monthly active users, reducing bundle load time by 45%.',
        'Engineered real-time telemetry dashboard using WebSockets, handling 10,000+ events per second with zero dropped frames.',
        'Mentored 5 junior engineers and established automated CI/CD code quality checks, increasing test coverage from 60% to 92%.',
      ],
    },
    {
      id: 'exp-2',
      company: 'CloudScale Inc',
      position: 'Full Stack Engineer',
      location: 'Austin, TX',
      startDate: '2019-06',
      endDate: '2021-12',
      current: false,
      description: 'Developed scalable API integrations and cloud backend services.',
      highlights: [
        'Designed Node.js microservices hosted on AWS Lambda & DynamoDB, reducing server infrastructure costs by $35k annually.',
        'Implemented OAuth2 authentication & RBAC user permissions system used by 200+ enterprise enterprise clients.',
        'Spearheaded migration from legacy monolith to React SPA, boosting user conversion by 28%.',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      institution: 'University of California, Berkeley',
      degree: 'Bachelor of Science',
      fieldOfStudy: 'Computer Science',
      location: 'Berkeley, CA',
      startDate: '2015-08',
      endDate: '2019-05',
      current: false,
      gpa: '3.85 / 4.0',
      description: 'Dean’s Honors List, President of Software Engineering Club.',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'DevFlow - Developer Productivity Platform',
      description:
        'An open-source AI dashboard that aggregates GitHub pull requests, Jira tasks, and deployment stats into a unified view.',
      techStack: ['React', 'TypeScript', 'Node.js', 'Tailwind CSS', 'OpenAI API'],
      link: 'https://devflow.demo.app',
      github: 'github.com/alexmorgan/devflow',
      startDate: '2023-03',
      endDate: '2023-08',
    },
    {
      id: 'proj-2',
      name: 'OmniSearch - Fast Vector Search Engine',
      description:
        'Lightweight in-memory vector database written in TypeScript for fast semantic similarity lookups.',
      techStack: ['TypeScript', 'Node.js', 'Vector Embeddings', 'Docker'],
      link: 'https://npmjs.com/package/omni-search',
      github: 'github.com/alexmorgan/omnisearch',
      startDate: '2022-09',
      endDate: '2022-11',
    },
  ],
  skills: [
    {
      id: 'skill-cat-1',
      categoryName: 'Languages & Frameworks',
      skills: ['TypeScript', 'JavaScript (ES6+)', 'React.js', 'Next.js', 'Node.js', 'Python', 'HTML5/CSS3', 'Tailwind CSS'],
    },
    {
      id: 'skill-cat-2',
      categoryName: 'Backend & Cloud',
      skills: ['Express.js', 'REST APIs', 'GraphQL', 'PostgreSQL', 'MongoDB', 'Redis', 'AWS (Lambda, S3, EC2)', 'Docker'],
    },
    {
      id: 'skill-cat-3',
      categoryName: 'Tools & Testing',
      skills: ['Git / GitHub', 'Jest', 'React Testing Library', 'Cypress', 'Vite', 'Webpack', 'CI/CD Pipelines'],
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      issueDate: '2023-04',
      credentialId: 'AWS-ASA-948123',
    },
  ],
  languages: [
    { id: 'lang-1', language: 'English', proficiency: 'Native' },
    { id: 'lang-2', language: 'Spanish', proficiency: 'Intermediate' },
  ],
  achievements: [
    {
      id: 'ach-1',
      title: 'First Place - SF Hackathon 2023',
      description: 'Awarded 1st place out of 120 teams for building an AI-powered accessibility audio assistant.',
      date: '2023-10',
    },
  ],
  interests: [
    { id: 'int-1', name: 'Open Source Development' },
    { id: 'int-2', name: 'UI/UX Design' },
    { id: 'int-3', name: 'Marathon Running' },
  ],
  sectionOrder: [
    'personal',
    'summary',
    'experience',
    'skills',
    'projects',
    'education',
    'certifications',
    'languages',
    'achievements',
    'interests',
  ],
  enabledSections: {
    personal: true,
    summary: true,
    experience: true,
    education: true,
    projects: true,
    skills: true,
    certifications: true,
    languages: true,
    achievements: true,
    interests: true,
  },
  theme: {
    templateId: 'modern',
    primaryColor: '#0c8ce9',
    fontFamily: 'inter',
    fontSize: 'md',
    spacing: 'normal',
  },
  atsScore: 88,
});
